query PrDetailsQuery($owner: String!, $repo: String!, $oid: Int!) {
    repository(owner: $owner, name: $repo) {
        pullRequest(number: $oid) {
            title
            headRefName
            headRefOid
            baseRefName

            commits(last: 100) {
                nodes {
                    commit {
                        oid
                        messageHeadline
                        committedDate
                        # Combines check runs (e.g. GitHub Actions) and commit statuses (e.g. Buildkite), like the GitHub UI.
                        statusCheckRollup {
                            state
                        }

                        # Only for the workflow runs, to find their artifacts.
                        checkSuites(last: 100, filterBy: {
                            appId: 15368 # GitHub Actions
                        }) {
                            nodes {
                                workflowRun {
                                    workflow {
                                        name
                                        id
                                    }
                                    databaseId
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
